name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    - name: Prepare
      run: |
        rustup target add wasm32-unknown-unknown
        cargo install wasm-gc
        cargo install wasm-bindgen-cli
    - name: Build
      run: |
        cargo build --verbose --target wasm32-unknown-unknown --release
        wasm-bindgen --target web --no-typescript --out-dir target/wasm32-unknown-unknown/release/ target/wasm32-unknown-unknown/release/wasm_sample.wasm
        wasm-gc target/wasm32-unknown-unknown/release/wasm_sample.wasm
    - name: Post
      run: tree -f
