name: wasm page - build and deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: wasm
      run: rustup target add wasm32-unknown-unknown
    - name: gc
      uses: baptiste0928/cargo-install@v1
      with:
        crate: wasm-gc
    - name: bindgen
      uses: baptiste0928/cargo-install@v1
      with:
        crate: wasm-bindgen-cli
    - name: build
      run: cargo build --target wasm32-unknown-unknown --release
    - name: strip
      run: wasm-bindgen --target web --no-typescript --out-dir target/wasm32-unknown-unknown/release/ target/wasm32-unknown-unknown/release/wasm_sample.wasm
    - name: strip
      run: wasm-gc target/wasm32-unknown-unknown/release/wasm_sample_bg.wasm
    - name: collect
      run: |
        cp target/wasm32-unknown-unknown/release/wasm_sample_bg.wasm www/wasm_sample_bg.wasm
        cp target/wasm32-unknown-unknown/release/wasm_sample.js www/wasm_sample.js
        mv www/wasm_sample.html www/index.html
    - name: yeet
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: www
